name: Lint Dockerfiles
on:
  pull_request:
    branches:
      - main

jobs:
  hadolint:
    runs-on: ubuntu-latest
    name: Hadolint
    steps:
      - name: Run hadolint
        uses: hadolint/hadolint-action@v3.1.0
        with:
          Dockerfile: Dockerfile
       
